### ISSUE TITLE
/lovelive?ed=2056报错

### ISSUE THREAD

**Issue by PHCSJC** [teddysun/xray-plugin#24]
1.8.0版本没有这个问题，加不加都可以正常运行
1.8.9版本加了这个参数就会报错，不加不报错
ss-redir -s aa.bb.cc -p 443 -l 1090 -b 0.0.0.0 -k aaaaaaa -m rc4-md5 --mtu 1200 --fast-open --plugin xray-plugin --plugin-opts "path=/?ed=2056;tls;mux=2;host=aa.bb.cc"
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xc0943e]

goroutine 6 [running]:
github.com/xtls/xray-core/transport/internet/websocket.(*delayDialConn).LocalAddr(0xc00014ee68?)
	<autogenerated>:1 +0x1e
github.com/xtls/xray-core/proxy/freedom.(*Handler).Process(0xc0002e5ad0, {0xf28098, 0xc00011c280}, 0xc000118100, {0xf268f0, 0xc0002f6a80})
	github.com/xtls/xray-core@v1.8.9/proxy/freedom/freedom.go:175 +0x637
github.com/xtls/xray-core/common/mux.(*DialingWorkerFactory).Create.func1({0x7f6177275dc8, 0xc0002e5ad0}, {0xf268f0, 0xc0002f6a80}, {0xf208c0, 0xc0000100c0})
	github.com/xtls/xray-core@v1.8.9/common/mux/client.go:156 +0x18e
created by github.com/xtls/xray-core/common/mux.(*DialingWorkerFactory).Create in goroutine 40
	github.com/xtls/xray-core@v1.8.9/common/mux/client.go:150 +0x1fd
 2024-03-28 17:29:12 ERROR: plugin service exit unexpectedly
 2024-03-28 17:29:12 INFO: error on terminating the plugin.
```

**Comment by peng5545** [comment]
try 

`/?ed\\\\=2056 or /?ed\\=2056`

**Comment by PHCSJC** [comment]
@peng5545
I have test version 1.8.11
```
/?ed\\\\=2056      <==== is ok
/?ed\\=2056         <==== is bad
```
